<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>d80d214c-aaf0-4864-9465-ac022a47bf3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-header']/div/nav/div/div/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.c-header-navigation__primary-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e2ad6ac2-a959-4c99-8fb3-b31a0113efaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-header-navigation__primary-link</value>
      <webElementGuid>22eb5ee2-27db-41db-87a9-65b531cd2fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://account.clio.com?cta=top-nav-na</value>
      <webElementGuid>60204655-4372-4444-8433-e2046dbc072e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-trigger</name>
      <type>Main</type>
      <value>click</value>
      <webElementGuid>2a043e8f-d11a-44e3-8051-779a2856b487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tracking-action</name>
      <type>Main</type>
      <value>Login Link</value>
      <webElementGuid>b5f65d94-79bf-47ee-adc3-bb34528ecac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>91c40b01-0165-4e4b-94cd-97c49b360fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/div[@class=&quot;c-page-header l-page-header js-header-container&quot;]/nav[@class=&quot;c-header-navigation&quot;]/div[@class=&quot;l-container&quot;]/div[@class=&quot;grid-middle-noGutter&quot;]/div[@class=&quot;col-12&quot;]/ul[@class=&quot;c-header-navigation__items c-header-navigation__items--secondary&quot;]/li[@class=&quot;c-header-navigation__item
		
		is-login
		js-nav-item&quot;]/a[@class=&quot;c-header-navigation__primary-link&quot;]</value>
      <webElementGuid>de36626e-39de-4225-97cc-f5e1e3ab65df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-header']/div/nav/div/div/div/ul/li[3]/a</value>
      <webElementGuid>39ef1eae-6a45-4ba8-abf1-23e4624c606b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>fb8ad493-e07a-4ab4-9620-7bc72a3e054c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Australia'])[1]/following::a[1]</value>
      <webElementGuid>cc59572b-033a-40b0-a813-ce0ace86f928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ireland'])[1]/following::a[2]</value>
      <webElementGuid>3c2d2018-2ad5-49fc-9203-128a5d4e44e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try For Free'])[1]/preceding::a[2]</value>
      <webElementGuid>f2362a3c-482c-458e-bbcf-e36949ef0872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start a 7 day free trial of Clio.'])[1]/preceding::a[3]</value>
      <webElementGuid>f1ccb112-f4f0-48c3-9faf-750610640f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>b498350f-2d62-409c-bc71-eefaa3ad0dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://account.clio.com?cta=top-nav-na')]</value>
      <webElementGuid>cb7280b5-45f4-478d-a58d-1d8e54d2288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>91945734-8681-4d13-b6cb-003422830e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://account.clio.com?cta=top-nav-na' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>9fb5d6aa-2959-411d-b7f1-7308d5e3bb49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
