<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_signuplast_name</name>
   <tag></tag>
   <elementGuidId>6dcc6c14-2685-4d52-a9d3-8ca230eeee2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clio_signup_last_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clio_signup_last_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b21e293-9255-436b-ba89-fcf3d4521c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clio_signup_last_name</value>
      <webElementGuid>f1ddc417-5797-4ab5-b0fb-557fe2e1e396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-signup-last-name</value>
      <webElementGuid>684e0e17-95e0-41e5-841d-1234ae3cb5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signup[last_name]</value>
      <webElementGuid>2ec8141c-fb62-4524-af79-f100b8e64577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbd08746-aaca-4cc6-aff5-21ce0c12187c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clio_signup_last_name&quot;)</value>
      <webElementGuid>d91f4c7d-127a-41c4-a131-72c3e7197cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clio_signup_last_name']</value>
      <webElementGuid>1b450642-2a51-4f30-b132-7b76869f472d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trial-form']/div/form/div[2]/input</value>
      <webElementGuid>0bd3e580-0d0f-4ba3-a0e2-184874dd9cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dd655352-5d99-4613-9f04-abd75d25fbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clio_signup_last_name' and @name = 'signup[last_name]' and @type = 'text']</value>
      <webElementGuid>d1dd7d9b-e130-44f1-a9b8-5e7c0cef5e78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
