<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_signupfirst_name</name>
   <tag></tag>
   <elementGuidId>0cacc864-59af-4412-9404-029f50bc1fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clio_signup_first_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clio_signup_first_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1064e5c6-89a0-403e-b921-2046008466d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clio_signup_first_name</value>
      <webElementGuid>5e8bd2dd-e92d-4c22-ab06-02d0ecb024fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-signup-first-name</value>
      <webElementGuid>902f0d46-950b-42e0-bb9d-d01d5a8189ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signup[first_name]</value>
      <webElementGuid>2d7613bf-047a-4e7f-b7ea-ea698e290a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2585f65-2f49-4f8f-9b6b-1567c97806be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clio_signup_first_name&quot;)</value>
      <webElementGuid>42eda0c2-9bd0-40fc-9a46-f8124ad95af2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clio_signup_first_name']</value>
      <webElementGuid>8c0694c6-17c4-4241-b622-2e45f66ed9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trial-form']/div/form/div/input</value>
      <webElementGuid>ed9775e5-25b8-453f-be74-d16ba7be795a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>08d14c8c-2fe0-42ef-9e98-fa3cb0f9d6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clio_signup_first_name' and @name = 'signup[first_name]' and @type = 'text']</value>
      <webElementGuid>a4cd447d-37a6-4c2c-82fa-e894423e44fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
