<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_signupphone_number</name>
   <tag></tag>
   <elementGuidId>30a4a711-a8b5-415b-98ff-48fbfeca0cf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clio_signup_phone_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clio_signup_phone_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c5302ad3-da42-4677-b3f7-ad36697c6801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clio_signup_phone_number</value>
      <webElementGuid>31962931-f64a-4d32-ae88-de8b26027c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-signup-phone-number</value>
      <webElementGuid>59dd0440-7467-42e8-a103-7871689db482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signup[phone_number]</value>
      <webElementGuid>5639da16-cf10-4f04-92dc-8cb99e0d2970</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>622cdf3a-c64a-4ffb-bab2-104e952a1bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>eg. +1 123 456 7890</value>
      <webElementGuid>9beaa909-313b-434c-a382-0b1ed7412332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clio_signup_phone_number&quot;)</value>
      <webElementGuid>31e6a16b-4cb2-4a97-a727-5b0f797d5988</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clio_signup_phone_number']</value>
      <webElementGuid>7957fce1-877d-4c03-8228-fca613cf9d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trial-form']/div/form/div[4]/input</value>
      <webElementGuid>d5898e20-af9f-416a-9504-2e906f51fddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>049a2f48-cd37-4904-bda2-2c63201df2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clio_signup_phone_number' and @name = 'signup[phone_number]' and @type = 'text' and @placeholder = 'eg. +1 123 456 7890']</value>
      <webElementGuid>09aaccab-eeea-4759-a85f-8ec3d90a261f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
