<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_signupemail</name>
   <tag></tag>
   <elementGuidId>87c27d43-4152-4fab-99ff-c55378042f30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clio_signup_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#clio_signup_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52f447e7-4dab-4793-8814-d016a6846938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clio_signup_email</value>
      <webElementGuid>98b43aff-3b57-4950-ad10-675058b45d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-signup-email</value>
      <webElementGuid>fd931190-c9e5-41c4-a336-5d1b082dec68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signup[email]</value>
      <webElementGuid>6329f9ff-b075-49eb-933d-c6ba23d24677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>fc071054-e09e-4981-ae4a-0f6ba5855730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clio_signup_email&quot;)</value>
      <webElementGuid>ae0c0a0b-3f3e-4b72-88c6-49db569f8f72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clio_signup_email']</value>
      <webElementGuid>a7f19590-8f31-404c-ab51-00d2f411d696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trial-form']/div/form/div[3]/input</value>
      <webElementGuid>a67a4348-f1c6-4b79-af58-5564a9979872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>4609e665-00c5-43c1-bcba-dcb5ab6904ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clio_signup_email' and @name = 'signup[email]' and @type = 'email']</value>
      <webElementGuid>9ea3d3f7-f7f2-4e59-9cd2-9e8ffd817561</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
